### ISSUE TITLE
Launcher update problem

### ISSUE THREAD

**Issue by firerike** [Jyberion/fallen-storyv83#26]
![IMG_20200815_152025](https://user-images.githubusercontent.com/69373835/90307715-71a9cb80-dec8-11ea-9aa0-337ed41ba325.jpg)
![IMG_20200815_150214](https://user-images.githubusercontent.com/69373835/90307720-81291480-dec8-11ea-97ca-871141c9512c.jpg)

Pc1-Updated half way will not responding, pc-2 error can not update

**Comment by Jyberion** [comment]
Download The New Launcher from the site your using the old Version of it
