### ISSUE TITLE
Boss Rush - Gaga NPC time issue

### ISSUE THREAD

**Issue by elGalletas** [Jyberion/fallen-storyv83#9]
I believe this Boss Rush PQ takes like 1:30 hours, well thats something, because when you enter now it only gives you 5 minutes in total. Please fix this.
![image](https://user-images.githubusercontent.com/22891772/89721338-f913ae00-d9a1-11ea-93ab-97af561af5ad.png)

**Comment by Jyberion** [comment]
this is Right for the PQ
